#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
export SCIENCEWORLD_HOME="${SCIENCEWORLD_HOME:-/data/wdy/ScienceWorld/official-ScienceWorld}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export PATH="${CONDA_PREFIX:-/data/wdy/.conda/envs/steppo}/bin:${PATH}"

MODEL_PATH="${SCIENCEWORLD_MODEL_PATH:-Qwen/Qwen3-4B-Instruct-2507}"
DATA_ROOT="${SCIENCEWORLD_DATA_ROOT:-$PROJECT_DIR/data/scienceworld}"
RUN_TIMESTAMP="$(date -u +%Y%m%d_%H%M%S)"
EXP_NAME="${EXP_NAME:-scienceworld_grpo_${RUN_TIMESTAMP}}"
python3 -m arft.main_agent_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.norm_adv_by_std_in_grpo=True \
    data.train_files="$DATA_ROOT/train.parquet" \
    data.val_files="$DATA_ROOT/test_in_train.parquet" \
    data.train_batch_size=16 \
    data.max_prompt_length=8192 \
    data.max_response_length=4096 \
    data.filter_overlong_prompts=True \
    data.truncation=error \
    data.return_raw_chat=True \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.policy_loss.loss_mode=vanilla \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.2 \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.loss_agg_mode=seq-mean-token-mean \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.agent.agent_flow_config_path="$PROJECT_DIR/recipe/scienceworld/base.yaml" \
    actor_rollout_ref.rollout.agent.default_agent_flow=scienceworld_agent \
    actor_rollout_ref.rollout.agent.num_workers=4 \
    actor_rollout_ref.rollout.trace.backend=mlflow \
    actor_rollout_ref.rollout.trace.token2text=True \
    actor_rollout_ref.rollout.trace.max_samples_per_step_per_worker=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.enable=False \
    custom_reward_function.path=recipe/scienceworld/reward_fn.py \
    custom_reward_function.name=compute_score \
    critic.enable=False \
    algorithm.use_kl_in_reward=False \
    algorithm.gamma=0.99 \
    trainer.critic_warmup=0 \
    trainer.logger='["console","swanlab","mlflow"]' \
    trainer.project_name=ScienceWorld_StepPO \
    trainer.experiment_name="$EXP_NAME" \
    trainer.validation_data_dir="$PROJECT_DIR/outputs/scienceworld_validation/$EXP_NAME" \
    trainer.rollout_data_dir="$PROJECT_DIR/outputs/scienceworld_rollout/$EXP_NAME" \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.val_before_train=True \
    trainer.save_freq=50 \
    trainer.test_freq=5 \
    trainer.max_actor_ckpt_to_keep=3 \
    trainer.total_epochs=5 \
    "$@"
